[book]
title = 'Learn Programming language'
authors = ['neuxdotdev']
description = 'Learn Any Programming language'
language = 'en'
text-direction = 'ltr'

[rust]
edition = '2024'

[build]
build-dir = 'book'  
create-missing = false
use-default-preprocessors = true  

[output.html]
default-theme = 'light'
preferred-dark-theme = 'coal'
smart-punctuation = true
definition-lists = true
admonitions = true
mathjax-support = true
no-section-label = false
git-repository-url = 'https://github.com/neuxdotdev/learn.git'
git-repository-icon = 'fab-github'
edit-url-template = 'https://github.com/neuxdotdev/learn/edit/main/{path}'
site-url = 'https://neuxdotdev.github.io/learn/'
cname = 'learn.neuxdotdev.github.io'
sidebar-header-nav = true

[output.html.print]
enable = true
page-break = true 

[output.html.playground]
editable = true   
copyable = true          
copy-js = true
line-numbers = true
runnable = true

[output.html.search]
enable = true
use-boolean-and = true   # multiple search terms must all match
boost-title = 2          # ranking boost factor for matches in headers
boost-hierarchy = 1      # ranking boost factor for matches in page names
boost-paragraph = 1      # ranking boost factor for matches in text
expand = true            # partial words will match longer terms
copy-js = true           # include Javascript code for search